### ISSUE TITLE
Spinouts not working

### ISSUE THREAD

**Issue by RyanCR03** [LogicTechCorp/NetherEx-Archive#130]
the spinouts are just sitting in thornstalks not moving at all or damaging the player

**Comment by LogicTechCorp** [comment]
This issue has been fixed in newer versions.

**Comment by Insculpo** [comment]
Spinouts in 12.2 are still not working.  It is not clear if this is because later versions broke them again or if other mods are interfering with their behavior (Special AI in particular is suspect)
