### ISSUE TITLE
JSON Crash 

### ISSUE THREAD

**Issue by Gunner76th** [LogicTechCorp/NetherEx-Archive#192]
I have recently started helping players resolve crash reports and such, and one issue that keeps popping up is a JSON issue in regards to NetherEx. The crash reports that an "invalid first character for a JSON object" however I am unable to identify which JSON file is in question, and there doesn't appear to be any that is directly related to NetherEx. This crash is still present even after an update to NetherEx-1.12.2-2.0.13

Link to crash report: https://paste.dimdev.org/goyururido.mccrash

**Comment by Gunner76th** [comment]
So after working with a player, it seems that for some reason the .json files in the ./config/netherex/trades/ folder are all blank. This is causing netherex to crash out as it is expecting data. One suggested change to the mod would be to have it do a check of the .json file, and if it detects the file is invalid, have it delete the file in question and generate a new .json with default values during startup. I know this is possible as several other mods that use .json files as config files do this already.

**Comment by LogicTechCorp** [comment]
This should be fixed in the latest release. Can you confirm by deleting all of the contents in one of the json configs and try launching the game.

**Comment by Gunner76th** [comment]
I can confirm this problem is still present in 2.0.13 of NetherEx. I cleared both the brewer.json from trades and ruthless_sands.json from biomes and got this crash: 
https://pastebin.com/K9N0KCSq

**Comment by Gunner76th** [comment]
restoring the json files allowed the client to load without any problems.

**Comment by LogicTechCorp** [comment]
The latest version is 2.0.14. It was released a few hours ago.

**Comment by Gunner76th** [comment]
Ahh ok, did not know that.

**Comment by Gunner76th** [comment]
@LogicTechCorp I just tested release 2.0.14 this morning, and I am sad to inform  you that the crash occurred again. 
http://www.pastebin.com/rZWDvx9W

In this test, I cleared all of the data from the brewer.json file as before, but for the ruthless_sands.json the only thing I did was deleted the { at the beginning of the file, since that is technically the thing the crash report is saying is missing. 

I reran the pack with only the brewer.json file cleared, and ruthless_sands.json fixed and validated and there were no issues. So it seems that *IF* the json is completely blank the updated version is able to successfully fix the problem and allow the pack to load (it deleted the bad/empty file and replaced it with a valid one). However, if the json file is simply missing the { at the beginning of the file as the crash technically states, then the entire process falls over as before and crashes out. Is it possible to have the mod check to see that the json is valid in its entirety instead of just checking to see if its filesize is =0 ?

**Comment by LogicTechCorp** [comment]
This should now be correctly resolved in version 2.0.15.

**Comment by Gunner76th** [comment]
I work tonight, but I can test and confirm in the morning. Ill will update with findings

**Comment by Gunner76th** [comment]
So I just ran tested 2.0.15 using the same methodology as above, clearing the brewer.json and removing the { from the ruthless_sands.json files. I am pleased to say that the client started up without any issues. Upon inspection of the files and folders, I now see the old "broken" files have been renamed to end in .backup and a new usable file has been create to replace it. 

As this allows the client to load, and is able to both check for invalid .json data files and replace them if needed to ensure client loading, I would call this issue closed. Thank you for your help and work in fixing this issue.
